### PR TITLE
added instruction to build&run local docker API server for development

### PR DESCRIPTION
**Pull request by olegtaranenko**

### CODE REVIEW

**Comment by yardenshoham** [comment]
This PR uses old names, I have changed them in #27

**Comment by mahnouman** [comment]
Hello @olegtaranenko please fix the conflict and consider @yardenshoham comment above, thank you.

**Comment by olegtaranenko** [comment]
Conflicts are resolved

**Review by yardenshoham — CHANGES_REQUESTED** [review]
Looks good at a quick glance, the names have changed though.
sow-rest-api -> k8-rebuild-rest-api
sow-rest-UI -> k8-rebuild-file-drop

**Comment by yardenshoham** [comment]
@mahnouman why did you merge it. The instructions are not correct. They use old names.

**Pull request merged**
